store:
  # data-only container
  image: postgres:latest # reuse postgres container
  container_name: db_store
  volumes:
    - /var/lib/postgresql/data
  command: "true"

postgres:
  image: postgres
  container_name: pg_db
  ports:
    - 5432:5432
  volumes_from:
    - store # connect postgres and the data-only container
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=todo_json_api_db

api:
  container_name: app
  build: ./api
  ports:
    - 3000:3000
  volumes:
    - ./api:/go/src/github.com/lucatironi/todo_json_api
  links:
    - postgres:db
  environment:
    - DB_ADDR=db
    - DB_PORT=5432
    - DB_NAME=todo_json_api_db
    - DB_USER=postgres
    - DB_PSWD=postgres
    - PORT=3000
